# Generated by Django 4.2.1 on 2023-06-08 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftweb', '0004_product_discount_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('countdown_time', models.DurationField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('extra_feature', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='premium_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftweb.premiumproduct'),
        ),
        migrations.AddField(
            model_name='payment',
            name='premium_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftweb.premiumproduct'),
        ),
    ]
