# Generated by Django 4.2.1 on 2023-06-08 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('giftweb', '0005_premiumproduct_cartitem_premium_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumproduct',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
