# Generated by Django 4.2.1 on 2023-06-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftweb', '0006_premiumproduct_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumproduct',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
