# Generated by Django 4.2.1 on 2023-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftweb', '0007_premiumproduct_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog_images')),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('read_more', models.URLField()),
            ],
        ),
    ]
