# Generated by Django 4.2.1 on 2023-06-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftweb', '0008_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_more',
            field=models.CharField(default='GiftCard', max_length=255),
        ),
    ]
