# Generated by Django 4.2.1 on 2023-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftweb', '0010_alter_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
